### ISSUE TITLE
Errors running in strict mode

### ISSUE THREAD

**Issue by di5abled** [pixotech/labcoat#3]
When I generate Patternalb with PHP strict mode active I get a lot of warnings like:

`Strict standards: Only variables should be passed by reference in ...\vendor\pixo\labcoat\src\Styleguide\Navigation\Navigation.php on line 29` 

But activating strict mode is necessary to detect errors in our twig templates, like wrong `variable-names` see: https://github.com/twigphp/Twig/issues/1967

**Comment by mattsharkey** [comment]
If you update to version 1.0.1, you shouldn't see any more errors.
